ingress:
  enabled: true
  className: traefik
  hosts:
    - host: gitea.home.lab 
      paths:
        - path: /
          pathType: Prefix
persistence:
  enabled: true
  storageClass: "local-path"

